#!/bin/sh
is_first_boot=`uci -q get zz_config.@status[0].first_boot`
if test $is_first_boot -gt 0; then
#echo -e "m28cm28c\nm28cm28c" | (passwd root)
uci set system.@system[0].hostname='M28C'
uci commit system
uci del dhcp.lan.ra_slaac
uci set network.lan.ipaddr='10.0.0.1'
uci add_list network.lan.ip6class='3_1_2v6'
uci add_list network.lan.ip6class='4_1_2v6'
uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/alpha'
uci set cpufreq.global.set='1'
uci set cpufreq.cpufreq.minfreq0='600000'
uci set cpufreq.cpufreq.maxfreq0='1608000'
uci commit
/etc/init.d/network reload
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0.ssid='M28C'
uci set wireless.default_radio0.encryption='psk2+ccmp'
uci set wireless.default_radio0.key='12345678'
uci commit wireless
/etc/init.d/network reload
wifi
uci -q set zz_config.@status[0].first_boot=0
uci commit zz_config
fi

sed -i "s?set wireless\.default_radio\${devidx}\.ssid=LEDE?set wireless\.default_radio\${devidx}\.ssid=\'M28C\'?g" /lib/wifi/mac80211.sh
sed -i "s?set wireless\.default_radio\${devidx}\.encryption=none?set wireless\.default_radio\${devidx}\.encryption=\'psk2+ccmp\'\n\t\t\tset wireless\.default_radio\${devidx}\.key=\'12345678\'?g" /lib/wifi/mac80211.sh

uci set alpha.@navbar[2].name='nlbw'
uci set alpha.@navbar[2].enable='Enable'
uci set alpha.@navbar[2].icon='/www/luci-static/alpha/zz/icon/navbar/bandwidth.png'
uci set alpha.@navbar[2].address='/cgi-bin/luci/admin/services/nlbw'
uci set alpha.@navbar[3].name='Modem'
uci set alpha.@navbar[3].icon='/www/luci-static/alpha/gaya/icon/navbar/modem.png'
uci set alpha.@navbar[3].address='/cgi-bin/luci/admin/modem/qmodem'
uci set alpha.@navbar[4].name='Wireless'
uci set alpha.@navbar[4].icon='/www/luci-static/alpha/zz/icon/navbar/wifi.png'
uci set alpha.@navbar[4].address='/cgi-bin/luci/admin/network/wireless'
uci commit alpha
